# Minimal Crisp configuration.
# Extend this with any project-specific configurations.

crisp:
  version: "0.1"
  project_name: "Crisp CLI Agile Framework"
  output_directory: "docs"
  project_dir: ""
  crisp_dir: ""
  cache_dir: ""
  artifact_type:
    backlog:
      description:
      template: template/backlog.template
    session:
      description:
      template: template/session.template
    sprint:
      description:
      template: template/sprint.template
